### ISSUE TITLE
Ability to list issues in several projects

### ISSUE THREAD

**Issue by ecksun** [ankitpokhrel/jira-cli#143]
I would like to list issues spanning multiple projects, for example corresponding to this JQL query:

    project in (APP, WEB, AI) AND labels in (backend)

Perhaps by providing a comma separated list to `--project`?

**Comment by ankitpokhrel** [comment]
@ecksun Right now we are binding JQL to a single project context. I think it will be better to provide a way to execute any valid JQL. Since project is a required field what we can do is:
- Check if `project` key exist in provided JQL
- If yes, we will use the query as is
- If not, we will append currently configured project to the query

It should then allow you to use any query combination.

**Comment by ecksun** [comment]
Ah, so that would mean that this would NOT be possible:

    jira issue list --label backend --project APP,WEB,AI

but

    jira issue list --jql 'project in (APP, WEB, AI) AND labels in (backend)'

would?

That works, not as convenient but JQL is not that bad to write
