### ISSUE TITLE
netrc configuration not picked up

### ISSUE THREAD

**Issue by marinjurjevic** [ankitpokhrel/jira-cli#357]
**Describe the bug**

I am trying to initialise using `netrc`. I created `~/.netrc` file with required fields. When I run `~/go/bin/jira init` I get prompted for e-mail. 
I'm not using $JIRA_API_TOKEN env variable and per instructions [here](https://github.com/ankitpokhrel/jira-cli/discussions/356), the next option is netrc file. 
Is there additional step I'm missing here? 

**Please provide following details**
1. JiraCLI Version:
    ```
   (Version="main", GitCommit="7d0b0c0f529758a56f809e09986bb713e497b1d4", CommitDate="2022-04-30T08:04:07+00:00", GoVersion="go1.18", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    Atlassian Jira [Project Management Software](https://www.atlassian.com/software/jira) (v8.3.0#803001-sha1:679cb7f)
    ```
3. What operating system are you using? Also mention version.
    ```
    OS: Manjaro 21.2.6 Qonos
    Kernel: x86_64 Linux 5.15.32-1-MANJARO
    ```
4. What terminal are you using? Also mention version.
    ```
    rxvt-unicode (urxvt) v9.26 - released: 2021-05-14
    ```

**To Reproduce**

1. jira init
2. Select Cloud
3. I get prompted for e-mail.

**Expected behavior**

I expect for init to succeed without additional steps
**Screenshots**

**Additional context**

Maybe you could print which method (token/netrc/keyring) is selected during initialisation.

**Comment by ankitpokhrel** [comment]
Hi @marinjurjevic, current `.netrc` implementation looks for the combination of `machine` name and `login` to get the token so email is required before the tool can get the token. This also means you can setup token for multiple users in the same `.netrc` file.

// cc: @adolsalamanca since you worked on this

**Comment by marinjurjevic** [comment]
> Hi @marinjurjevic, current `.netrc` implementation looks for the combination of `machine` name and `login` to get the token so email is required before the tool can get the token. 

I've setup the credentials per aforementioned instructions:
```
machine <full-jira-server-host-url>
login <username>
password <password>
```

I'm registered as external user on the Jira server so I don't have e-mail/token combination. I've setup different tools (e.g. VSCode extension) with username/password successfully. 

If e-mail is required, then I suggest your emphasize that in the [instructions](https://github.com/ankitpokhrel/jira-cli/discussions/356).

**Comment by ankitpokhrel** [comment]
@marinjurjevic just to be clear when I said email is required I meant `login` section of `.netrc` and that can either be email or username based on your setup. In your case you can use your username.

**Comment by adolsalamanca** [comment]
Hello!

Regarding this comment:
> If e-mail is required, then I suggest your emphasize that in the [instructions](https://github.com/ankitpokhrel/jira-cli/discussions/356).

As you can see [here](https://github.com/ankitpokhrel/jira-cli/discussions/356) email or username is already specified as a requirement.

> login <login-email-or-username>

I would consider this issue as solved :)

Thanks

**Comment by komar007** [comment]
Looks like even though the Jira host passed to `jira-cli init` must be a URL, the netrc file is looked up by just the host (no scheme). The template `<full-jira-server-host-url>` is misleading without clarification.

Then, after `jira-cli init` has succeeded, no other commands work, because the username is stored in the generated config file in lowercase (why?), which results in failed lookup in .netrc and a misleading error message as if the tool was used for the first time.

I am using tag `v1.7.0`.

A workaround is to use lowercase login which works with my server (local installation).
