### ISSUE TITLE
Gtk-Message: Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by khskekec** [ankitpokhrel/jira-cli#547]
**Describe the bug**
After clicking enter to open an issue in the browser "Gtk-Message: 16:09:48.965: Failed to load module "canberra-gtk-module" appears randomly on the screen. Switching between the issues by using the arrow keys removes it again

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="1.2.0", GitCommit="9d8a0afd75b68aa519367f93c240429117cc4090", CommitDate="2022-12-16T10:53:08+00:00", GoVersion="go1.18.3", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server?
```
    SERVER INFO
Version:         1001.0.0-SNAPSHOT
Build Number:    100213
Deployment Type: Cloud
Default Locale:  en_US
```
3. What operating system are you using? Also mention version.
    ```
    Ubuntu 22.10
    ```
4. What terminal are you using? Also mention version.
    ```
    Alacritty  0.12.0-dev
    ```

**To Reproduce**

1. Just open list of any issues: `jira issue list`
2. Click on a row to open the issue in the browser
3. See weird screenshot

**Expected behavior**
View is not destroyed by gtk messages

**Screenshots**
![image](https://user-images.githubusercontent.com/70414755/211589716-c7599a7c-1c84-49cc-a0e0-70a46bf54113.png)

**Additional context**

**Comment by ankitpokhrel** [comment]
Hi @khskekec, I am not sure about this. This looks something specific to your system. I will leave this open for now in case others have similar issues and could help.

**Comment by colindean** [comment]
When `jira-cli` opens a browser, it executes `xdg-open` on Linux, and it's up to the OS to know how to open a browser from that. In general, that means Firefox on Ubuntu.

This is a side effect of Firefox looking for a particular shared library when it starts up. It doesn't _need_ the library.

Take a look at 

* [How to fix error: Failed to load module "canberra-gtk-module"](https://askubuntu.com/questions/1175572/how-to-fix-error-failed-to-load-module-canberra-gtk-module)
* [Ubuntu 22.04 LTS: Starting firefox through terminal Error "cannot change mount " & Failed to load module "canberra-gtk-module", How to solve it?](https://askubuntu.com/questions/1409575/ubuntu-22-04-lts-starting-firefox-through-terminal-error-cannot-change-mount)

for some things to try. This problem is outside of `jira-cli`'s scope, tbh.

**Comment by ankitpokhrel** [comment]
Closing as this seems to be system dependent and out of scope of this project.
