### ISSUE TITLE
jira open fails in dockerized version

### ISSUE THREAD

**Issue by PawelDefee** [ankitpokhrel/jira-cli#656]
**Describe the bug**

Hi, I am running the dockerized version of jira-cli. Setup and connection to Cloud is succesful, am able to list projects. But then trying "jira open", I get:
~ # jira open XYZ
Error: exec: "xdg-open,x-www-browser,www-browser": executable file not found in $PATH

**Please provide following details**
1. JiraCLI Version:

(Version="v1.4.0", GitCommit="eb842e18014303a575fde8e19508b3c7c13982c5", CommitDate="2023-05-09T07:09:45+00:00", GoVersion="go1.19.9", Compiler="gc", Platform="linux/amd64")

2. Are you using Jira cloud or on-premise jira server?

Version:         1001.0.0-SNAPSHOT
Build Number:    100234
Deployment Type: Cloud
Default Locale:  en_GB

3. What operating system are you using? Also mention version.

Ubuntu 22.04. Note: running dockerized jira-cli

4. What terminal are you using? Also mention version.

Bash shell.

**To Reproduce**

I am running the dockerized version of jira-cli. Setup and connection to Cloud is succesful, am able to list projects. But then trying "jira open", I get:
~ # jira open XYZ
Error: exec: "xdg-open,x-www-browser,www-browser": executable file not found in $PATH

**Expected behavior**

Navigate to the project.

**Screenshots**

None

**Additional context**

None

**Comment by Dmitrev** [comment]
This is isn't really possible out-of-the-box with Docker, because it would have to communicate with your OS to open the browser, and it can't because it's isolated.

So just install it natively would be my advice.

If you don't mind getting your hands dirty, you can try something like this:
https://stackoverflow.com/questions/54437534/docker-open-a-url-in-the-host-browser

Though you are on your own with the latter option, as it's more of a power user option.
