### ISSUE TITLE
WSL2: can't open jira issue in the browser

### ISSUE THREAD

**Issue by maksimf** [ankitpokhrel/jira-cli#668]
**Describe the bug**
Whenever I press Enter while viewing a list of issues I get:

    
    user-open error: dial unix /run/user/1000/bus: connect: no such file or directory

**Please provide following details**
1. JiraCLI Version:
    ```
    1.4.0
    ```
2. Are you using Jira cloud or on-premise jira server?
    ```
    cloud
    ```
3. What operating system are you using? Also mention version.
    ```
    WSL2 running Ubuntu-22.04
    ```
4. What terminal are you using? Also mention version.
    ```
    Windows Terminal -> zsh + tmux
    ```

**To Reproduce**

1. `jira-cli issue list`
2. Press Enter
3. See error

**Expected behavior**
Browser page opens, showing jira issue web page 

**Screenshots**
![image](https://github.com/ankitpokhrel/jira-cli/assets/860283/d8a2e04d-579d-40b2-8054-d640e6d695f2)

**Additional context**
90% sure this has to do with the fact that I'm using WSL2

**Comment by westopy** [comment]
Get `wslu` from https://github.com/wslutilities/wslu for your WSL2 setup and include `export BROWSER=wslview` in your bashrc/zshrc. The wslview tool opens links in your Windows default browser.

**Comment by maksimf** [comment]
Unfortunately, this yields the same result

**Comment by westopy** [comment]
What happens when you enter `wslview https://google.com` in WSL?

**Comment by maksimf** [comment]
It works, i.e. google.com is opened with my default browser

**Comment by maksimf** [comment]
My bad, I've forgot to set env variable. The behaviour has changed: I do not see the error anymore, but nothing happens

**Comment by westopy** [comment]
The above steps worked for me on Arch Linux. I can reproduce your issue on a new install of Ubuntu 22.04.2 on WSL 2, where wslview works, but hitting enter on an issue causes no error and no action.

**Comment by westopy** [comment]
I believe the issue is related to the snap running in WSL2, since it works correctly when running the binary directly.

- I cleared the `BROWSER` and `JIRA_BROWSER` variables which means `xdg-open` is used first as default (`sudo apt install xdg-utils` if it is missing)
- Confirm that `xdg-open https://google.com` opens the URL in the default windows browser
- Download the relevant .tar.gz from releases, and run the binary `./jira`
- On hitting Enter on an issue, the URL opens in the Windows browser

I would recommend removing the snap and trying an alternative installation method, since there is an issue with the Snap on WSL2.

**Comment by maksimf** [comment]
I can confirm this is working. Thank you very much for the assistance

**Comment by lucastheisen** [comment]
FWIW, i use this bash script which i call `open`:

```sh
#!/bin/bash

if [[ -v WSL_DISTRO_NAME ]]; then
  powershell.exe -Command "& {Start-Process '$1'}"
else
  exec open "$@"
fi
```

Then just

```sh
export BROWSER=open
```
