### ISSUE TITLE
Can't build, undefined error with github.com/yuin/goldmark

### ISSUE THREAD

**Issue by ewag** [ankitpokhrel/jira-cli#84]
➜  jira_go go get github.com/ankitpokhrel/jira-cli/cmd/jira
go: found github.com/ankitpokhrel/jira-cli/cmd/jira in github.com/ankitpokhrel/jira-cli v0.0.0-20210323162451-7ea7fb0ad495
# github.com/charmbracelet/glamour/ansi
../../go/pkg/mod/github.com/charmbracelet/glamour@v0.2.0/ansi/renderer.go:75:15: undefined: "github.com/yuin/goldmark/extension/ast".KindFootnoteBackLink

➜  jira_go go version
go version go1.15.7 darwin/amd64

Tried to work around error by installing goldmark with go get, but still receiving the same error.

**Comment by ankitpokhrel** [comment]
Hi @ewag,

Thank you for reporting. This is because one of the dependencies [broke backwards compatibility](https://github.com/charmbracelet/glamour/pull/103) and unfortunately `go get` doesn't honor [`replace` directive in `go.mod`](https://github.com/ankitpokhrel/jira-cli/blob/master/go.mod#L41). I will bump the [glamour](https://github.com/charmbracelet/glamour) version once its available. For now, you can clone the repo and build it locally using `make install`. 

Also, PRs are welcome!

**Comment by ankitpokhrel** [comment]
@ewag installation should work now!
