### ISSUE TITLE
add navigation commands in --help

### ISSUE THREAD

**Issue by gennaro-tedesco** [ankitpokhrel/jira-cli#98]
I have been trying out and using `jira-cli`: it is awesome!

I have noticed that the `--help` does not list the navigation commands as per [here](https://github.com/ankitpokhrel/jira-cli#navigation): do you think it is useful to add them to the help, so that users do not have to come to the GitHub url in case they forget (I find myself using `c` and `CTRL+K` often but I forget which is which)?

**Comment by ankitpokhrel** [comment]
I don't want to make `help` too bloated since the navigation list can grow in the future. What we can do however is put some common navigation commands and add a link to GitHub readme for more details.

Navigation information is available in some commands like `jira sprint list` and `jira epic list` at the moment.

<img width="1101" alt="Screenshot 2021-05-21 at 18 44 42" src="https://user-images.githubusercontent.com/2364546/119171317-b1f43680-ba64-11eb-8d4c-d00f0d185ebb.png">

**Comment by gennaro-tedesco** [comment]
You're right, that would be the preferred option. Good enough though that they are available already in `jira epic list` or so!
